SELECT ROUND(salary ,2 ) as monthlysalary
from employees;

select * from employees;

UPDATE employees 
set salary = 14583.258 
where salary = 24000;

SELECT first_name , last_name , round(salary/12 , 2) as monthlysalary from employees;

SELECT MANAGER_ID , MIN(SALARY)
FROM employees
where MANAGER_ID IS NOT NULL
GROUP BY MANAGER_ID;

SELECT DEPARTMENT_ID , AVG(SALARY) AS AVGsalary
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 10;

SELECT FIRST_NAME , LAST_NAME 
FROM EMPLOYEES
WHERE SALARY > 
	(SELECT SALARY FROM EMPLOYEES
	WHERE EMPLOYEE_ID = 163);

SELECT FIRST_NAME , LAST_NAME , SALARY , DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY IN
	(SELECT MIN(SALARY)
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID);

SELECT FIRST_NAME , LAST_NAME , EMPLOYEE_ID , SALARY
FROM EMPLOYEES
WHERE MANAGER_ID = 
	(SELECT EMPLOYEE_ID
	FROM EMPLOYEES
	WHERE FIRST_NAME = 'PAYAM');




